[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
chimken_run = "FQZhPRFBoCn1ZvvMBUb14sdUFHw8g3GTFLbQjP5vuw1a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kj_dv/.config/solana/local.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
